In [23]:
import pandas as pd
# 1 dimentional Series
mobiles = pd.Series(["iPhone","Nokia","Samsung","OPPO"])
mobiles

0     iPhone
1      Nokia
2    Samsung
3       OPPO
dtype: object

In [24]:
# 1 dimentional Series 
bag = pd.Series(["pens","pencils","notebooks","papers"])
bag

0         pens
1      pencils
2    notebooks
3       papers
dtype: object

In [25]:
# 2 dimentional data
data_frame = pd.DataFrame({"Electronics":mobiles,"Items":bag})
data_frame

  Electronics      Items
0      iPhone       pens
1       Nokia    pencils
2     Samsung  notebooks
3        OPPO     papers

In [26]:
# How to import Data 
# Most common Files Format CSV Comma Seprated Values

# import 
heart_disease_data = pd.read_csv("heart.csv")
heart_disease_data.head(9)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0

In [28]:
# export
heart_disease_data.to_csv("modified_heart_disease_data.csv")

In [29]:
# again import 
heart_disease_data = pd.read_csv("modified_heart_disease_data.csv")
heart_disease_data.head(9)

,Unnamed: 0,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0

In [30]:
# if you don't want to add index you just write :
heart_disease_data.to_csv("modified_heart_disease_data_2.csv", index = False)
heart_disease_data = pd.read_csv("modified_heart_disease_data_2.csv")
heart_disease_data.head(9)
# if you don't add index = False then its add more index line

,Unnamed: 0,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0

How to Describe data

In [ ]:
# Attributes

# attribute is not a function
# attribute is not followed by paranthesis
# examples :

heart.dtypes

columns = heart.columns
columns

index = heart.index
index

# Functions
# function is followed by paranthesis
# examples :

heart.describe() # works only for numerical data
heart.info()
heart.mean() # works only for numerical data