<a href="https://colab.research.google.com/github/MehmoodCoder/Ai_Ml_Course/blob/main/Ai_Ml/Main/Sk_learn_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Getting the data ready
# choosing Machine Learning Model
# Fit Model
# Evaluate Model
# Imporve Model
# Saving the Model

In [ ]:
import pandas as pd

***Getting Ready data***

In [ ]:
url = "https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv"
df = pd.read_csv(url)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
# create x

x = df.drop("target", axis=1)
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [ ]:
# create y

y = df["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

***Choosing ML Model***

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

***Fitting Model***

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
clf.fit(x_train, y_train)

RandomForestClassifier()

***Evaluate Model***

In [ ]:
y_predicted = clf.predict(x_test)
y_predicted

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1])

In [ ]:
# Evaluation

clf.score(x_train, y_train)

1.0

In [ ]:
clf.score(x_test, y_test)

0.8131868131868132

***Improve Model***

In [ ]:
for i in range(10,210,10):
  print(f"Running Model with {i} estimators.")
  clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
  print(f"Accuracy is : {(clf.score(x_test, y_test))*100}")

#  we find 180 gives us good accuracy

Running Model with 10 estimators.
Accuracy is : 74.72527472527473
Running Model with 20 estimators.
Accuracy is : 76.92307692307693
Running Model with 30 estimators.
Accuracy is : 81.31868131868131
Running Model with 40 estimators.
Accuracy is : 81.31868131868131
Running Model with 50 estimators.
Accuracy is : 76.92307692307693
Running Model with 60 estimators.
Accuracy is : 78.02197802197803
Running Model with 70 estimators.
Accuracy is : 79.12087912087912
Running Model with 80 estimators.
Accuracy is : 75.82417582417582
Running Model with 90 estimators.
Accuracy is : 75.82417582417582
Running Model with 100 estimators.
Accuracy is : 81.31868131868131
Running Model with 110 estimators.
Accuracy is : 79.12087912087912
Running Model with 120 estimators.
Accuracy is : 76.92307692307693
Running Model with 130 estimators.
Accuracy is : 80.21978021978022
Running Model with 140 estimators.
Accuracy is : 79.12087912087912
Running Model with 150 estimators.
Accuracy is : 76.92307692307693
Running Model with 160 estimators.
Accuracy is : 76.92307692307693
Running Model with 170 estimators.
Accuracy is : 79.12087912087912
Running Model with 180 estimators.
Accuracy is : 76.92307692307693
Running Model with 190 estimators.
Accuracy is : 79.12087912087912
Running Model with 200 estimators.
Accuracy is : 76.92307692307693

***Saving Model***

In [ ]:
import pickle
pickle.dump(clf,open("Heart_Disease_Predictor.pkl","wb"))

In [ ]:
load_model = pickle.load(open("/content/Heart_Disease_Predictor.pkl", "rb"))
load_model.score(x_test,y_test)

0.7692307692307693

In [ ]:
# Getting the data ready
# choosing Machine Learning Model
# Fit Model
# Evaluate Model
# Imporve Model
# Saving the Model

 Getting the data ready

 1 split your data into features and labels , (independent vs dependent variable), x,y

 2 filling missing values

 3 converting data types

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
url = "https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv"
df = pd.read_csv(url)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
x = df.drop("target", axis=1)
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [ ]:
y = df['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_test,Y_train = train_test_split(x,y,test_size = 0.25)

In [ ]:
url = 'https://raw.githubusercontent.com/MehmoodCoder/Ai_Ml_Course/refs/heads/main/Ai_Ml/Data/phone.csv'
phone = pd.read_csv(url)
phone

     brand          model  storage_gb  ram_gb  price_pkr condition
0  Samsung     Galaxy S23         256       8  Rs.195000       New
1    Apple      iPhone 17         512       8  Rs.520000      Used
2   Xiaomi  Redmi Note 13         256       8   Rs.55000       New
3  Infinix        Note 40         256      12   Rs.48000       New
4   Realme            C67         128       8   Rs.39000       New
5    Tecno       Camon 30         256       8   Rs.42000      Used
6     Vivo           Y200         128       8   Rs.62000       New
7     Oppo            A78         256       8   Rs.58000      Used
8  OnePlus      Nord CE 3         256      12   Rs.95000       New
9   Google        Pixel 7         128       8  Rs.115000      Used

In [ ]:
phone.dtypes

brand         object
model         object
storage_gb     int64
ram_gb         int64
price_pkr     object
condition     object
dtype: object

In [ ]:
phone['price_pkr'] = phone['price_pkr'].str.replace('Rs.','').astype(int)
phone['price_pkr'].dtypes

dtype('int64')

In [ ]:
phone

     brand          model  storage_gb  ram_gb  price_pkr condition
0  Samsung     Galaxy S23         256       8     195000       New
1    Apple      iPhone 17         512       8     520000      Used
2   Xiaomi  Redmi Note 13         256       8      55000       New
3  Infinix        Note 40         256      12      48000       New
4   Realme            C67         128       8      39000       New
5    Tecno       Camon 30         256       8      42000      Used
6     Vivo           Y200         128       8      62000       New
7     Oppo            A78         256       8      58000      Used
8  OnePlus      Nord CE 3         256      12      95000       New
9   Google        Pixel 7         128       8     115000      Used

In [ ]:
a = phone.drop('price_pkr',axis = 1)
b = phone['price_pkr']

a_test,a_train, b_test,b_train = train_test_split(a,b, test_size = 0.2)
a,b

(     brand          model  storage_gb  ram_gb condition
 0  Samsung     Galaxy S23         256       8       New
 1    Apple      iPhone 17         512       8      Used
 2   Xiaomi  Redmi Note 13         256       8       New
 3  Infinix        Note 40         256      12       New
 4   Realme            C67         128       8       New
 5    Tecno       Camon 30         256       8      Used
 6     Vivo           Y200         128       8       New
 7     Oppo            A78         256       8      Used
 8  OnePlus      Nord CE 3         256      12       New
 9   Google        Pixel 7         128       8      Used,
 0    195000
 1    520000
 2     55000
 3     48000
 4     39000
 5     42000
 6     62000
 7     58000
 8     95000
 9    115000
 Name: price_pkr, dtype: int64)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

features = ['brand','model','condition']
hottie = OneHotEncoder()

transformer = ColumnTransformer([("One_hottie",hottie,features)], remainder = 'passthrough')

transformaer_a = transformer.fit_transform(a)
transformaer_a

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 50 stored elements and shape (10, 24)>

In [ ]:
# 2nd method for transforming

transformer_b = pd.get_dummies(phone[['brand','model','condition']])
transformer_b

,brand_Apple,brand_Google,brand_Infinix,brand_OnePlus,brand_Oppo,brand_Realme,brand_Samsung,brand_Tecno,brand_Vivo,brand_Xiaomi,...,model_Camon 30,model_Galaxy S23,model_Nord CE 3,model_Note 40,model_Pixel 7,model_Redmi Note 13,model_Y200,model_iPhone 17,condition_New,condition_Used
0,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
2,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
4,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
7,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
8,False,False,False,True,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
9,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True

In [ ]:
# refit model

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf = RandomForestClassifier(n_estimators=160)


a_train,a_test, b_train,b_test = train_test_split(transformaer_a,b, test_size = 0.5, random_state=45)
clf.fit(a_train,b_train)

RandomForestClassifier(n_estimators=160)

In [ ]:
clf.score(a_test,b_test)

0.0

In [ ]:
clf.score(a_train,b_train)

1.0

In [ ]:
transformaer_a.shape

(10, 24)

In [2]:
import pandas as pd
Missing_phone = pd.read_csv("https://raw.githubusercontent.com/MehmoodCoder/Ai_Ml_Course/main/Ai_Ml/Data/mising_values_phone.csv")
Missing_phone

     brand          model  storage_gb  ram_gb  price_pkr condition
0  Samsung     Galaxy S23         NaN     8.0  Rs.195000       NaN
1    Apple      iPhone 17       512.0     8.0        NaN      Used
2   Xiaomi  Redmi Note 13       256.0     8.0   Rs.55000       New
3  Infinix            NaN       256.0    12.0   Rs.48000       New
4   Realme            C67       128.0     8.0        NaN       New
5    Tecno            NaN       256.0     8.0   Rs.42000      Used
6     Vivo           Y200       128.0     NaN   Rs.62000       New
7      NaN            A78       256.0     8.0   Rs.58000      Used
8  OnePlus      Nord CE 3         NaN     NaN   Rs.95000       New
9   Google        Pixel 7       128.0     NaN  Rs.115000       NaN

In [3]:
Missing_phone.isna().sum()

brand         1
model         2
storage_gb    2
ram_gb        3
price_pkr     2
condition     2
dtype: int64

In [ ]:
# we never apply model on data with NaN

In [4]:

# fill missing values NaN

Missing_phone["brand"] = Missing_phone["brand"].fillna("missing")
Missing_phone["model"] = Missing_phone["model"].fillna("missing")
Missing_phone["condition"] = Missing_phone["condition"].fillna("missing")

Missing_phone["storage_gb"] = Missing_phone["storage_gb"].mean()
Missing_phone["ram_gb"] = Missing_phone["ram_gb"].mean()

# drop price

Missing_phone.dropna(inplace = True)

In [5]:
Missing_phone.isna().sum()

brand         0
model         0
storage_gb    0
ram_gb        0
price_pkr     0
condition     0
dtype: int64

In [6]:

# method 2

Missing_phone_2 = pd.read_csv("https://raw.githubusercontent.com/MehmoodCoder/Ai_Ml_Course/main/Ai_Ml/Data/mising_values_phone.csv")
Missing_phone_2

     brand          model  storage_gb  ram_gb  price_pkr condition
0  Samsung     Galaxy S23         NaN     8.0  Rs.195000       NaN
1    Apple      iPhone 17       512.0     8.0        NaN      Used
2   Xiaomi  Redmi Note 13       256.0     8.0   Rs.55000       New
3  Infinix            NaN       256.0    12.0   Rs.48000       New
4   Realme            C67       128.0     8.0        NaN       New
5    Tecno            NaN       256.0     8.0   Rs.42000      Used
6     Vivo           Y200       128.0     NaN   Rs.62000       New
7      NaN            A78       256.0     8.0   Rs.58000      Used
8  OnePlus      Nord CE 3         NaN     NaN   Rs.95000       New
9   Google        Pixel 7       128.0     NaN  Rs.115000       NaN

In [7]:
Missing_phone_2.isna().sum()

brand         1
model         2
storage_gb    2
ram_gb        3
price_pkr     2
condition     2
dtype: int64

In [8]:


Missing_phone_2 = Missing_phone_2.dropna(subset = ["price_pkr"])

# it remove complete row in which price_pkr contains NaN value


Missing_phone_2.isna().sum()

brand         1
model         2
storage_gb    2
ram_gb        3
price_pkr     0
condition     2
dtype: int64

In [9]:
Missing_phone_2

     brand          model  storage_gb  ram_gb  price_pkr condition
0  Samsung     Galaxy S23         NaN     8.0  Rs.195000       NaN
2   Xiaomi  Redmi Note 13       256.0     8.0   Rs.55000       New
3  Infinix            NaN       256.0    12.0   Rs.48000       New
5    Tecno            NaN       256.0     8.0   Rs.42000      Used
6     Vivo           Y200       128.0     NaN   Rs.62000       New
7      NaN            A78       256.0     8.0   Rs.58000      Used
8  OnePlus      Nord CE 3         NaN     NaN   Rs.95000       New
9   Google        Pixel 7       128.0     NaN  Rs.115000       NaN

In [10]:
# split data

X = Missing_phone_2.drop("price_pkr", axis = 1)
Y = Missing_phone_2["price_pkr"]

In [11]:
X

     brand          model  storage_gb  ram_gb condition
0  Samsung     Galaxy S23         NaN     8.0       NaN
2   Xiaomi  Redmi Note 13       256.0     8.0       New
3  Infinix            NaN       256.0    12.0       New
5    Tecno            NaN       256.0     8.0      Used
6     Vivo           Y200       128.0     NaN       New
7      NaN            A78       256.0     8.0      Used
8  OnePlus      Nord CE 3         NaN     NaN       New
9   Google        Pixel 7       128.0     NaN       NaN

In [12]:
Y

0    Rs.195000
2     Rs.55000
3     Rs.48000
5     Rs.42000
6     Rs.62000
7     Rs.58000
8     Rs.95000
9    Rs.115000
Name: price_pkr, dtype: object

In [13]:
# imputation
# filling values with sklearn

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# fill categorical values with missing and numeric with mean

In [15]:


Categorical_features = SimpleImputer(strategy = "constant", fill_value = "missing")
Numerical_features = SimpleImputer(strategy = "mean")

In [16]:
# define columns

cat_cols = ["brand","model","condition"]
num_cols = ["storage_gb","ram_gb"]


Imputer = ColumnTransformer([
    ("Categorical_feature", Categorical_features,  cat_cols),
    ("Numeric_feature", Numerical_features, num_cols)
])

In [17]:



Filled_X = Imputer.fit_transform(X)
Filled_X

array([['Samsung', 'Galaxy S23', 'missing', 213.33333333333334, 8.0],
       ['Xiaomi', 'Redmi Note 13', 'New', 256.0, 8.0],
       ['Infinix', 'missing', 'New', 256.0, 12.0],
       ['Tecno', 'missing', 'Used', 256.0, 8.0],
       ['Vivo', 'Y200', 'New', 128.0, 8.8],
       ['missing', 'A78', 'Used', 256.0, 8.0],
       ['OnePlus', 'Nord CE 3', 'New', 213.33333333333334, 8.8],
       ['Google', 'Pixel 7', 'missing', 128.0, 8.8]], dtype=object)

In [18]:


Phone_Data = pd.DataFrame(Filled_X,  columns = ["brand","model","condition","storage","ram"])

In [19]:
Phone_Data

     brand          model condition     storage   ram
0  Samsung     Galaxy S23   missing  213.333333   8.0
1   Xiaomi  Redmi Note 13       New       256.0   8.0
2  Infinix        missing       New       256.0  12.0
3    Tecno        missing      Used       256.0   8.0
4     Vivo           Y200       New       128.0   8.8
5  missing            A78      Used       256.0   8.0
6  OnePlus      Nord CE 3       New  213.333333   8.8
7   Google        Pixel 7   missing       128.0   8.8